version: "3.7"

services:
  strongfaculty-server:
    build:
      context: server
    image: strongfaculty-server:${COMPOSE_TAG_NAME:-stage}
    container_name: strongfaculty-server
    networks:
      - default
    ports:
      - "${SERVER_PORT:-5000}:${SERVER_PORT:-5000}"
    depends_on:
      - strongfaculty-mongo

  strongfaculty-client:
    build:
      context: client
    image: strongfaculty-client:${COMPOSE_TAG_NAME:-stage}
    container_name: strongfaculty-client
    networks:
      - default
    ports:
      - "${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}"
    depends_on:
      - strongfaculty-server

  strongfaculty-mongo:
    image: mongo
    container_name: strongfaculty-mongo
    networks: 
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-supersecret}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-strongfaculty}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME:-strongfaculty}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD:-secret}
    ports:
      - "27017:27017"
    volumes:
      # 20190601 - fix for https://github.com/docker-library/mongo/issues/329#issuecomment-460858099
      - ./mongo-user.sh:/docker-entrypoint-initdb.d/mongo-user.sh:ro
      - /tmp/strongfaculty-db:/data/db

  strongfaculty-mongoexp:
    image: mongo-express
    container_name: strongfaculty-mongoexp
    networks: 
      - default
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER:-strongfaculty-mongo}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD:-supersecret}
    ports:
      - "8081:8081"
    depends_on:
      - strongfaculty-mongo

  strongfaculty-webserver:
    image: nginx:mainline-alpine
    container_name: strongfaculty-webserver
    networks:
      - default
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - strongfaculty-server

  strongfaculty-certbot:
    image: certbot/certbot
    container_name: strongfaculty-certbot
    networks: 
      - default
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - strongfaculty-webserver
    command: certonly --webroot --webroot-path=/var/www/html --email martin.stefko@protonmail.com --agree-tos --no-eff-email -d strongfaculty.com  -d www.strongfaculty.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/views
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /var/www/StrongFacultyCS/dhparam/
      o: bind


networks:
  default:
    driver: bridge

